import {
  SiReact,
  SiTailwindcss,
  SiNextdotjs,
  SiGit,
  SiAstro,
  SiJavascript,
  SiFigma,
  SiTypescript,
  SiHtml5,
  SiVite,
  SiCss3,
  SiReactrouter,
  SiVsco,
  SiVercel,
  SiNotion,
  SiPrisma,
} from 'react-icons/si'
import { IoCloudDownloadOutline } from 'react-icons/io5'

const iconNameMap = new Map([
  [SiReact, 'React'],
  [SiTailwindcss, 'Tailwind'],
  [SiNextdotjs, 'Next.js'],
  [SiGit, 'Git'],
  [SiAstro, 'Astro'],
  [SiJavascript, 'JavaScript'],
  [SiFigma, 'Figma'],
  [SiTypescript, 'TypeScript'],
  [SiHtml5, 'HTML5'],
  [SiVite, 'Vite'],
  [SiCss3, 'CSS3'],
  [SiVsco, 'VsCode'],
  [SiVercel, 'Vercel'],
  [SiNotion, 'Notion'],
  [SiPrisma, 'Prisma'],
  [SiReactrouter, 'React Router'],
  [IoCloudDownloadOutline, 'Download'],
])

export {
  SiReact,
  SiTailwindcss,
  SiNextdotjs,
  SiGit,
  SiAstro,
  SiJavascript,
  SiFigma,
  SiTypescript,
  SiHtml5,
  SiVite,
  SiCss3,
  SiReactrouter,
  SiVsco,
  SiVercel,
  SiNotion,
  SiPrisma,
  IoCloudDownloadOutline,
  iconNameMap,
}
